{ARO} minor CLI enhancements, including extension suppression
Azure/azure-cli pull request #15897
Opened 2020-11-12 22:16 UTC by dkorzuno

**Description**

The updates here are the latest development features to be added to Azure Red Hat OpenShift az cli client.

 - extension suppression
 - logging improvements
 - narrow permissions  

**Testing Guide**

None
These are the enhancements that we use for our Azure cli in the github.com/Azure/ARO-RP repository.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2020-11-12 22:17 UTC, dkorzuno commented
/cc @jim-minter

2020-11-12 23:56 UTC, yonzhan commented
ARO

2020-11-13 01:24 UTC, jim-minter requested changes
minor changes requested

2020-11-13 01:24 UTC, jim-minter commented on src/azure-cli/azure/cli/command_modules/aro/_help.py
> -    text: az aro create --resource-group MyResourceGroup --name MyCluster --vnet MyVnet --master-subnet MyMasterSubnet --worker-subnet MyWorkerSubnet --apiserver-visibility Private --ingress-visibili
@dkorzuno this shouldn't be removed here, it is in fact missing and should be added in the ARO-RP copy of _help.py

2020-11-13 01:24 UTC, jim-minter commented on src/azure-cli/azure/cli/command_modules/aro/custom.py
> +    rp_client_id = os.environ.get('AZURE_FP_CLIENT_ID', 'f1dd0a37-89c6-4e07-bcd1-ffd3d43d8875')
we should not read AZURE_FP_CLIENT_ID in this codebase, hard code to the uuid.  Probably keeping it as a constant, i.e. `FP_CLIENT_ID = 'f1dd0a37-89c6-4e07-bcd1-ffd3d43d8875'`, is clearer

2020-11-13 13:58 UTC, jim-minter approved these changes
lgtm - azure-cli team please merge.

2020-11-16 23:13 UTC, jim-minter commented
@fengzhou-msft bump

2020-11-17 07:55 UTC, fengzhou-msft approved these changes

2020-11-17 07:55 UTC, merged