[AppService] Allow Azure Functions Create to accept Python 3.9 parameters
Azure/azure-cli pull request #16020
Opened 2020-11-23 19:11 UTC by Hazhzeng

**Description**

Azure Functions team is going to support Python 3.9 in December, we need to allow customers to create Python 3.9 function app in azure-cli before the Python 3.9 announcement.

This is **NOT** an official Azure Functions Python 3.9 release.

cc: @gzuber, @Azure/fta-prodgroupaccess 

**Testing Guide**

Customer should be able to create Python 3.9
1. On Linux Consumption with `az functionapp create -g <resource_group> -n <app_name> -c <consumption_plan_location> -s <storage_account> --os-type linux --runtime python --runtime-version 3.9 --functions-version 3`
2. On Linux Dedicated/Premium with `az functionapp create -g <resource_group> -n <app_name> -p <dedicated_plan_name> -s <storage_account> --os-type linux --runtime python --runtime-version 3.9 --functions-version 3`

**History Notes**

[AppService] az functionapp create: accept "--runtime python" and  "--runtime-version 3.9" as Azure Functions v3 parameter

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2020-11-23 19:16 UTC, pragnagopa commented
@Hazhzeng - This is driven by updating stacks so that all tooling can be notified of the support.

Please send PR to updates to two repos:
1. Sample PR1: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/20  
2. Sample PR2 to udpate Ux: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/20

2020-11-23 19:17 UTC, pragnagopa commented on src/azure-cli/azure/cli/command_modules/appservice/_constants.py
> +PYTHON_VERSIONS = ['3.9', '3.8', '3.7', '3.6']
@gzuber - is this needed? versions should be coming from stacks right?

2020-11-23 19:22 UTC, pragnagopa commented on src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
> -                        "isHidden": false
Once changes to support python 3.9 are deployed to all regions in Azure, you need to send another PR to un-hide

2020-11-23 19:23 UTC, pragnagopa commented on src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
> -                        "isHidden": false
in other words - if changes are already deployed to Azure, no need to set the `isHidden` property - just setting preview to true is enough

2020-11-23 19:23 UTC, pragnagopa requested changes
Please send PRs to 
- https://github.com/Azure/azure-functions-ux/
- https://github.com/pragnagopa/azure-functions-supported-runtime-stacks

2020-11-23 20:25 UTC, Hazhzeng commented
CI fails with extension error but I haven't changed anything in extension though, please advise.
```
Please ensure you have network connection.
Error detail: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded
with url: /azure-cli-extension-index-v1 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:852)'),))
```

2020-11-23 20:27 UTC, pragnagopa approved these changes

2020-11-24 01:33 UTC, qwordy approved these changes

2020-11-24 01:38 UTC, gzuber approved these changes

2020-11-24 04:00 UTC, yonzhan commented
AppService

2020-11-25 18:09 UTC, Hazhzeng commented
Hi @qwordy, could you help me to re-run **Test Extensions Loading Python36** and see if it goes through. Not sure if this will block the merge? Thanks.

2020-11-26 03:18 UTC, qwordy commented
/azp run

2020-11-26 03:26 UTC, qwordy commented
> 
> 
> Hi @qwordy, could you help me to re-run **Test Extensions Loading Python36** and see if it goes through. Not sure if this will block the merge? Thanks.

Sure.

2020-11-26 07:07 UTC, merged

2020-12-01 21:36 UTC, Hazhzeng commented
Hi @qwordy, please mark this to S179 milestone.

2020-12-02 03:30 UTC, qwordy commented
> 
> 
> Hi @qwordy, please mark this to S179 milestone.

OK