{Doc} Add install extensions part for airgapped cloud guide
Azure/azure-cli pull request #16175
Opened 2020-12-07 09:26 UTC by fengzhou-msft

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2020-12-07 09:50 UTC, yonzhan commented
Doc

2020-12-07 09:55 UTC, yungezz commented on doc/use_cli_in_airgapped_clouds.md
> +We are working on solutions to make the installation and upgrade of Azure CLI easier in airgapped clouds. Before that is ready, you need to download the Azure CLI package with public internet access,
The top one is latest release, such as `Azure CLI 2.15.1`

2020-12-07 09:55 UTC, yungezz commented on doc/use_cli_in_airgapped_clouds.md
> +1. Replace `<version>` with the actual CLI version you need to use. On Ubuntu/Debian, replace `<distro>` with the result of the `lsb_release -cs` command.
```suggestion
1. Replace `<version>` with the actual CLI version you need to use, such as `2.15.1`. On Ubuntu/Debian, replace `<distro>` with the result of the `lsb_release -cs` command, such as xxx.
```

2020-12-07 09:55 UTC, yungezz commented on doc/use_cli_in_airgapped_clouds.md
> +on Windows Powershell.
An example metadata file is https://management.azure.com/metadata/endpoints?api-version=2019-05-01

2020-12-07 18:26 UTC, dbradish-microsoft requested changes
@fengzhou-msft , if airgapped clouds are going to be a growing trend, would you be okay with this information going into azure-docs-cli probably in the TOC under How-to guides?  We have similar information already over there, such as Work with Multiple Clouds.  Thoughts?

2020-12-10 07:32 UTC, qwordy approved these changes

2021-01-07 06:33 UTC, fengzhou-msft commented
@dbradish-microsoft this doc is for temporary workarounds in airgapped clouds under current situation. We will make improvements and when things are easier and more stable, we can show the content in ms doc as well.

2021-01-22 03:19 UTC, yungezz approved these changes

2021-01-22 03:22 UTC, merged