Update custom.py
Azure/azure-cli pull request #16251
Opened 2020-12-13 14:48 UTC by talalhaddad

Fix rcf.template_specs.delete If VersionID presented

**Description**
CLI command for delete Template specs is deleting the template specs instead of the provided version alone, else statement adder

**Testing Guide**
az ts delete -g RGName --n TSName -v 1.0 
this was deleting the template specs resource and not the version needed, now will delete the version alone in case version ID provided 

**History Notes**
[Template Specs] az command Delete: Fix version parameter issue.

2020-12-13 23:30 UTC, yonzhan commented
ARM

2020-12-16 05:39 UTC, jiasli commented
This is a bot spamming our repo. 

The change is also against the linter rule. 

https://dev.azure.com/azure-sdk/public/_build/results?buildId=652812&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8&l=107

```
src/azure-cli/azure/cli/command_modules/resource/custom.py:1900:4: R1705: Unnecessary "else" after "return" (no-else-return)
```

2020-12-16 05:40 UTC, jiasli requested changes
Should close.

2020-12-18 02:45 UTC, closed without merging

2020-12-18 02:46 UTC, zhoxing-ms commented
It was replaced by #16295