{Aladdin} add usage examples for module: keyvault monitor network privatedns resource storage vm
Azure/azure-cli pull request #16328
Opened 2020-12-21 06:13 UTC by azclibot

This PR is created by AladdinParser Pipeline. 

 ADO_BUILD_ID=660624 

 Against last commit of dev: https://github.com/Azure/azure-cli/commit/57a0b8101 

 Against last commit of Aladdin-src: https://github.com/Azure/azure-cli/commit/297c6f4be1cef5ae534efff36ddd397d9e37a150

2020-12-21 12:22 UTC, yonzhan commented
Aladdin

2021-01-14 03:20 UTC, kairu-ms requested changes

2021-01-14 03:20 UTC, kairu-ms commented on src/azure-cli/azure/cli/command_modules/network/_help.py
> +    crafted: true
Remove this example. It's the same as upper one.

2021-01-14 03:20 UTC, kairu-ms commented on src/azure-cli/azure/cli/command_modules/network/_help.py
> +    crafted: true
Remove this one. It's the same as upper one.

2021-01-14 03:20 UTC, kairu-ms commented on src/azure-cli/azure/cli/command_modules/network/_help.py
> +    crafted: true
Remove this one. It's the same as upper one.

2023-02-03 00:55 UTC, closed without merging