[AppService] Hotfix: az webapp config ssl import: fixing bug that causes failures on national clouds
Azure/azure-cli pull request #16701
Opened 2021-01-28 02:55 UTC by singlessis

**Description**

With the last a change, a bug was introduced that attempted to use the CertificateRegistration RP in national clouds, which causes a failure.

**Testing Guide**

az webapp config ssl import --resource-group rg --name app --key-vault kv --key-vault-certificate cert

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-01-28 07:00 UTC, yonzhan commented
AppService

2021-01-29 04:58 UTC, panchagnula commented on src/azure-cli/azure/cli/command_modules/appservice/custom.py
> +    if cloud_type.lower() == "AzureCloud".lower():
Is Azure Cloud public? if so this logic is incorrect. Note: the change expected is
client.app_service_certificate_orders -> is supported on public only so making this call should be avoided on all non-public clouds.

2021-01-29 04:58 UTC, panchagnula requested changes
Please confirm the logic for checking the environment is right

2021-01-29 23:20 UTC, singlessis commented
@qwordy @Juliehzl I am trying to write a test that runs in a national cloud, to track this scenario going forward, but it seems like the way I managed to get it working locally is not ideal, it might contain sensitive information. Is there a better way to run a test on a government cloud? thanks!

2021-01-31 05:28 UTC, panchagnula commented
> @qwordy @Juliehzl I am trying to write a test that runs in a national cloud, to track this scenario going forward, but it seems like the way I managed to get it working locally is not ideal, it might contain sensitive information. Is there a better way to run a test on a government cloud? thanks!

@qwordy  mainly is there a way we can run specific tests or all test on non public clouds. That way Sofi doesn't need to add a specific test for S-clouds?

2021-01-31 05:29 UTC, panchagnula approved these changes
Lets get the build to pass otherwise looks good to me.

2021-02-01 19:25 UTC, singlessis commented
> Lets get the build to pass otherwise looks good to me.

The build is failing because of the test I tried adding, I will remove it, and hopefully we can run the tests in national cloud

2021-02-02 07:29 UTC, qwordy commented
@singlesis Login to the cloud you want to test. Then run test lively. Replay test should be able to pass as long as live test can pass. If code in test case has sensitive information, I recommend deleting the test case. But, remember to make sure it can work in the expected cloud. If recording file has sensitive information, you can mark the test case as `live_only()`, then delete the recording file.

2021-02-02 07:49 UTC, qwordy approved these changes

2021-02-03 21:27 UTC, singlessis commented
@Juliehzl could you take a look?

2021-02-04 00:24 UTC, merged