[AppService]: fix ##8743- az webapp deploy
Azure/azure-cli pull request #16715
Opened 2021-01-28 18:12 UTC by Kotasudhakarreddy

**Description**

#8743- az webapp deploy
**Testing Guide**

az webapp deploy --resource-group ResouceGroup --name AppName --src-path SourcePath --type static --target-path staticfiles/test.txt

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-01-28 19:54 UTC, jvano commented
:shipit:

2021-01-28 20:20 UTC, shrishrirang approved these changes

2021-01-29 01:50 UTC, yonzhan commented
AppService

2021-01-29 01:53 UTC, panchagnula commented on src/azure-cli/azure/cli/command_modules/appservice/_help.py
> +helps['webapp deploy'] = """
Is this not needed for function app?

2021-01-29 01:56 UTC, panchagnula commented on src/azure-cli/azure/cli/command_modules/appservice/commands.py
> +        g.custom_command('deploy', 'perform_onedeploy', validator=validate_onedeploy_params)
This command should have 'preview' tag

2021-01-29 01:56 UTC, panchagnula requested changes
Changes look good.
but we are missing
1. test cases
2. function app equivalent support - assuming this works for function apps as well.
3. Also add "PREVIEW" tag attribute to this command.

2021-01-29 12:04 UTC, Kotasudhakarreddy commented
> Changes look good.
> but we are missing
> 
> 1. test cases
> 2. function app equivalent support - assuming this works for function apps as well.
> 3. Also add "PREVIEW" tag attribute to this command.

working on Testcases. Will address the remaining review comments in my next PR.

2021-01-29 19:17 UTC, panchagnula commented
> > Changes look good.
> > but we are missing
> > 
> > 1. test cases
> > 2. function app equivalent support - assuming this works for function apps as well.
> > 3. Also add "PREVIEW" tag attribute to this command.
> 
> working on Testcases. Will address the remaining review comments in my next PR.



> > Changes look good.
> > but we are missing
> > 
> > 1. test cases
> > 2. function app equivalent support - assuming this works for function apps as well.
> > 3. Also add "PREVIEW" tag attribute to this command.
> 
> working on Testcases. Will address the remaining review comments in my next PR.

One more thing to add is --slot support on the commands - especially if API supports this.

2021-02-04 09:06 UTC, Kotasudhakarreddy commented on src/azure-cli/azure/cli/command_modules/appservice/_help.py
> +helps['webapp deploy'] = """
Added for Functionapp too.

2021-02-05 14:25 UTC, Kotasudhakarreddy commented
@panchagnula - please review

2021-02-06 14:49 UTC, Kotasudhakarreddy commented on src/azure-cli/azure/cli/command_modules/appservice/commands.py
> +        g.custom_command('deploy', 'perform_onedeploy', validator=validate_onedeploy_params)
Added preview tag.

2021-02-18 21:50 UTC, panchagnula approved these changes
LGTM

2021-02-19 02:42 UTC, qwordy approved these changes

2021-02-19 02:43 UTC, merged