[AppService] az webapp up: Save defaults for "runtime" and "os_type" parameter
Azure/azure-cli pull request #17038
Opened 2021-02-22 20:35 UTC by calvinsID

**Description**

For `az webapp up` command, defaults are saved for "group", "sku", "appserviceplan", "location", "web" parameters.
Recently added parameters "runtime" and "os_type", however defaults weren't being saved for these parameters

**Testing Guide**
- Run `az webapp up` with --runtime or --os-type parameter
- On later runs of `az webapp up`, the overrided runtime/os_type parameters aren't being used since they weren't saved in defaults.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-02-22 23:44 UTC, yonzhan commented
AppService

2021-02-24 00:14 UTC, panchagnula requested changes
I am not sure what the purpose of this changes are?
if an app doesn't exist user should provide these values to override the defaults up makes?
if an app exists & command is used for re-deploymenr then we should just honor the values of the current app & try to override anything . Correct?

2021-02-24 00:14 UTC, panchagnula commented on src/azure-cli/azure/cli/command_modules/appservice/custom.py
> +        cmd.cli_ctx.config.set_value('defaults', 'os', os_name.lower())
Not sure what the purpose of these are - since runtime & Os are not universal defaults in Azure ?

2021-03-29 07:15 UTC, qwordy commented
@calvinsID Is this PR still active? Otherwise, I will close it.

2021-03-29 14:31 UTC, closed without merging