[FunctionApp] Updated stacks api json to add PowerShell on Linux in Functions
Azure/azure-cli pull request #17678
Opened 2021-04-14 01:18 UTC by stefanushinardi

**Description**

The PR is to add Powershell on linux offerings https://github.com/Azure/azure-cli/issues/17657
**Testing Guide**

Verified that now the command does not throw validation error when deploying with Linux os type. And also verified creation of both consumption and elastic premium plan

sample command:
```console
az functionapp create --name powershell-linux-premium-cli-create-shinardi --os-type Linux --runtime powershell --resource-group powershell-linux-cli-shinardi --functions-version 3 --storage-account powershelllinuxcli --plan ASP-pythonscaling-8a67

Application Insights "powershell-linux-premium-cli-create-shinardi" was created for this Function App. You can visit https://portal.azure.com/#resource/subscriptions/df6d3c16-321b-4f5b-a9de-c4ed04950b97/resourceGroups/powershell-linux-cli-shinardi/providers/microsoft.insights/components/powershell-linux-premium-cli-create-shinardi/overview to view your Application Insights component
```

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-04-14 01:19 UTC, stefanushinardi commented
cc: @Francisco-Gamino @AnatoliB @pragnagopa @gzuber Please review this PR. Thanks!

2021-04-14 05:38 UTC, yungezz approved these changes

2021-04-14 08:59 UTC, qwordy approved these changes

2021-04-14 15:39 UTC, pragnagopa commented on src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json
> +                        "isHidden": false
Please use: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/blob/master/LinuxFunctionsStacks.json

We want this stack to be hidden until we roll out functions host changes to support linux consumption

2021-04-14 15:39 UTC, pragnagopa requested changes
Please add stack as hidden. Also, need to add tests that check powershell stack

2021-04-14 21:01 UTC, gzuber commented
> Please add stack as hidden. Also, need to add tests that check powershell stack

Hey @stefanushinardi I sent you a message about the tests, let me know if I can help out! 😄

2021-04-16 00:10 UTC, stefanushinardi commented
@pragnagopa @gzuber Added that tests for powershell. Thanks @Hazhzeng to help fix the local setip

2021-04-16 00:39 UTC, gzuber approved these changes
Looks good!

2021-04-16 06:04 UTC, qwordy commented
@stefanushinardi Are we ready to merge?

2021-04-16 15:17 UTC, pragnagopa approved these changes
💯 Thanks @stefanushinardi

2021-04-16 17:02 UTC, stefanushinardi commented
@qwordy yup, thanks!

2021-04-19 03:39 UTC, merged