[AppService] az appservice domain create: Fix get correct domain agreements
Azure/azure-cli pull request #18622
Opened 2021-06-24 00:45 UTC by calvinsID

**Description**
Get correct domain agreements for user to acknowledge, in `az appservice domain create` command

Backend is introducing a validation API for domain creates, and domains created through CLI are passing in different agreements than what was expected causing the validation API to fail

**Testing Guide**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-06-24 04:45 UTC, yonzhan commented
AppService

2021-06-24 16:54 UTC, panchagnula requested changes
are there any tests we can add here to identify these issues?

2021-06-24 23:59 UTC, calvinsID commented
> are there any tests we can add here to identify these issues?

I don't think we can add a test for `domain create` since we aren't hooked up to GD test endpoints

2021-06-25 00:05 UTC, panchagnula commented
> > are there any tests we can add here to identify these issues?
> 
> I don't think we can add a test for `domain create` since we aren't hooked up to GD test endpoints

The question mainly was can we create a test to validate the values returned from the command are correct (like defaults) if possible? If not this LGTM

2021-06-25 00:34 UTC, calvinsID commented
> tion mainly was can we create a test to validate the values returned from the command are correct (li

Ah right there is a --dryrun option, let me add tests

2021-06-29 21:45 UTC, panchagnula approved these changes
Ship It

2021-06-30 05:34 UTC, Juliehzl commented on src/azure-cli/azure/cli/command_modules/appservice/appservice_domains.py
> +    from azure.mgmt.web.models import TopLevelDomainAgreementOption
please use get_models() as 3.  in https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#multi-api-aware-modules

2021-06-30 05:39 UTC, Juliehzl commented on src/azure-cli/azure/cli/command_modules/appservice/appservice_domains.py
> +        raise CLIError("Custom domain name '{}' is not available. Please try again "
please use error type in azclierror, e.g.
https://github.com/Azure/azure-cli/blob/3eea7fd773722b7a3c40b8115f29a3bad39b70bc/src/azure-cli-core/azure/cli/core/azclierror.py#L152-L154

2021-07-01 20:21 UTC, panchagnula commented
@Juliehzl this PR is needed for S189 as well - can you please sign-off & merge?

2021-07-02 01:13 UTC, merged