[AKS] Fix issues with parsing certain minor versions
Azure/azure-cli pull request #18727
Opened 2021-07-04 15:52 UTC by Volatus

**Description**
In some cases, the `kubectl` minor version can include non-numeric characters`20+`. (For example, #17769) This causes an issue parsing the minor version. This PR makes it so that all non-numeric characters are stripped out before parsing the version.

**Testing Guide**
`az aks check-acr --name {} --resource-group {} --acr {}`

**History Notes**
[AKS] az aks check-acr: Fix issues with parsing certain minor versions

Closes #17769
Closes #18314
Closes #18263
Closes #16936

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-07-04 23:22 UTC, yonzhan commented
AKS

2021-07-05 02:01 UTC, zhoxing-ms requested changes
Could you add related test for this change?

2021-07-05 12:57 UTC, Volatus commented
@zhoxing-ms What kind of test should this be? It technically doesn't need a cluster because it's just the client version of `kubectl` that has such behavior. Do I just do a unit test with sample JSON input?

2021-07-06 01:36 UTC, zhoxing-ms commented
@Volatus Could you test the case of passing in non-numeric characters when parsing the version?

2021-07-26 08:23 UTC, zhoxing-ms commented
@Volatus May I ask what's the update here?

2021-07-26 13:50 UTC, Volatus commented
> @Volatus May I ask what's the update here?

I'd like to finish this up but I'm not sure how to test it. The tests in the codebase seem like integration tests. Wouldn't this mean to test we'd need a specific version of `kubectl` on the host that has `+` as part of the version number?

2021-07-27 02:03 UTC, zhoxing-ms commented
> Wouldn't this mean to test we'd need a specific version of kubectl on the host that has + as part of the version number?

@Volatus Yes, exactly. We need to use tests to ensure that `az aks check-acr` doesn't crash when kubectl minor version includes non-numeric chars

2021-07-28 06:34 UTC, zhoxing-ms commented
@Volatus Any update?

2021-07-28 12:11 UTC, Volatus commented
> > Wouldn't this mean to test we'd need a specific version of kubectl on the host that has + as part of the version number?
> 
> @Volatus Yes, exactly. We need to use tests to ensure that `az aks check-acr` doesn't crash when kubectl minor version includes non-numeric chars

Right but how would I possibly write a test that uses a specific `kubectl` version to test this behavior?

2021-07-29 00:12 UTC, zhoxing-ms commented
@Volatus Hi
If you don't know how to write a test, please refer to the guideline https://github.com/Azure/azure-cli/blob/dev/doc/authoring_tests.md
If you don't know how to construct a kubectl minor version, CLI team should not be the right team to answer this question. You need to ask the relevant service team

2021-07-29 09:53 UTC, Volatus commented
> @Volatus Hi
> If you don't know how to write a test, please refer to the guideline https://github.com/Azure/azure-cli/blob/dev/doc/authoring_tests.md
> If you don't know how to construct a kubectl minor version, CLI team should not be the right team to answer this question. You need to ask the relevant service team

I'll read the documentation about testing and see what I can do.

2021-07-29 10:18 UTC, zhoxing-ms commented
I can merge this PR first. Please add relevant tests later

2021-07-29 10:18 UTC, zhoxing-ms approved these changes

2021-07-29 10:18 UTC, merged