[ACR] Fix some bugs on uncovered cmds
Azure/azure-cli pull request #18831
Opened 2021-07-13 05:16 UTC by rosanch

**Description**
I was still able to find some bugs related to the SDK update.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-07-13 05:29 UTC, yonzhan commented
ACR

2021-07-13 06:40 UTC, 00Kai0 requested changes

2021-07-13 06:40 UTC, 00Kai0 commented on src/azure-cli/azure/cli/command_modules/acr/scope_map.py
> +        actions = actions,
remove unexpected spaces:
```
    scope_map = ScopeMap(
        actions=actions,
        description=description
    )
```

2021-07-13 06:40 UTC, 00Kai0 commented
LGTM

2021-07-13 07:55 UTC, jsntcy commented on src/azure-cli/azure/cli/command_modules/acr/scope_map.py
> +        description = description
```suggestion
        actions=actions,
        description=description
```

2021-07-13 07:57 UTC, zhoxing-ms commented
There are no any recorded yaml files here. May I ask have you rerun the relevant tests?

2021-07-13 08:04 UTC, zhoxing-ms commented
By the way, the reason why these bugs have not been found before is because the tests do not cover these cases? If so, please add relevant tests~

2021-07-13 08:27 UTC, zhoxing-ms requested changes
I'd like to ask is this PR for hotfix? If so, please submit hotfix related PRs to the release branch. Please refer to this document for details [doc link](https://github.com/Azure/azure-cli/blob/main/doc/authoring_command_modules/README.md#hotfix-pr)

2021-07-13 09:16 UTC, 00Kai0 approved these changes

2021-07-13 16:32 UTC, northtyphoon approved these changes
LGTM

2021-07-13 20:26 UTC, rosanch commented
Connected-registry currently has no test at all.
Scope Map I'm not sure why it didn't have an update command covered in the tests. It seems it was token was the main group covered in the testing so scope-map wasn't fully covered.

2021-07-13 20:36 UTC, rosanch commented
@zhoxing-ms we want to include this in the hot release. But on top of the PR #18786 and I don't see that merged to the release branch. Wouldn't it make some merge conflict if I merge this change first?
cc: @northtyphoon

2021-07-14 06:13 UTC, zhoxing-ms commented
This change has been merged into the release branch by https://github.com/Azure/azure-cli/pull/18853. After hotfix is released, we will merge back to the dev branch, so close this PR first

2021-07-14 06:13 UTC, closed without merging

2021-07-14 06:34 UTC, 00Kai0 commented
Close it, because PR https://github.com/Azure/azure-cli/pull/18853 has included it.