[Batch] Update to API v2021-06-01
Azure/azure-cli pull request #19100
Opened 2021-08-02 23:33 UTC by cRui861

**Description**

Upgrade the Batch data plane to 11.0.0 and management plane to 16.0.0 (API version 2021-06-01).

**Testing Guide**

Testing the Batch module is described in the [README.md](https://github.com/Azure/azurecli/blob/dev/src/azurecli/azure/cli/command_modules/batch/tests/latest/README.md)

**History Notes**

[Batch] Upgrade batch data-plane to [azure-batch 11.0.0](https://pypi.org/project/azure-batch/)
[Batch] Upgrade batch management-plane to [azure-batch-mgmt 16.0.0](https://pypi.org/project/azure-mgmt-batch/16.0.0/)
[Batch] az batch account: Adds `--account-endpoint` property

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-08-02 23:55 UTC, yonzhan commented
Batch

2021-08-03 21:58 UTC, cRui861 commented
Hi @zhoxing-ms, we're looking to get these changes in before the next release. It would be great if this PR could get reviewed and approved before the cut-off for the next release happens (I believe it is this Thursday?). Thanks!

2021-08-04 01:36 UTC, zhoxing-ms commented
@cRui861 Hi, in fact, this sprint is over, and the next sprint will be released on 09-07

2021-08-04 01:41 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/batch/_help.py
> +long-summary: Terminates the specified job, marking it as completed. When a Terminate Job request is received, the Batch service sets the job to the terminating state. The Batch service then terminat
Please use the first person voice
```suggestion
long-summary: Terminate the specified job, marking it as completed. When a Terminate Job request is received, the Batch service sets the job to the terminating state. The Batch service then terminates any running tasks associated with the job and runs any required job release tasks. Then the job moves into the completed state. If there are any tasks in the job in the active state, they will remain in the active state. Once a job is terminated, new tasks cannot be added and any remaining active tasks will not be scheduled.
```

2021-08-04 01:45 UTC, zhoxing-ms requested changes
Could you please add some test cases for those new commands?

2021-08-04 17:18 UTC, gingi commented on src/azure-cli/azure/cli/command_modules/batch/_help.py
> +long-summary: Terminates the specified job, marking it as completed. When a Terminate Job request is received, the Batch service sets the job to the terminating state. The Batch service then terminat
Fixed.

2021-08-04 22:56 UTC, gingi commented
> Could you please add some test cases for those new commands?

I've added a few test cases for the new commands.

2021-08-05 03:09 UTC, zhoxing-ms approved these changes

2021-08-06 06:27 UTC, zhoxing-ms requested changes
@gingi If you want to release it in the next week, please submit this PR to the release branch, because we will launch the hot fix process for it.

2021-08-06 17:03 UTC, cRui861 commented
@zhoxing-ms Updated the branch to be merged into the `release` branch instead of `dev`.

2021-08-07 10:57 UTC, zhoxing-ms approved these changes

2021-08-07 10:57 UTC, merged