[AKS] Refactor acs module: refactor aks sub-command create part 1
Azure/azure-cli pull request #19118
Opened 2021-08-04 07:50 UTC by FumingZhang

**Description**

[DO NOT MERGE] Refactor aks sub-command create.
* Please refer to the sample PR#3743 in aks-preview to verify the effect of reuse.
* Please refer to this wiki for the details of the modification.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-08-04 08:28 UTC, yonzhan commented
AKS

2021-08-06 02:54 UTC, andyliuliming requested changes

2021-08-06 02:54 UTC, andyliuliming commented on src/azure-cli/azure/cli/command_modules/acs/custom.py
> +        self.context = AKSCreateContext()
could you please add some comments describing which kind of data should be stored to the context.
so people can follow.

2021-08-06 02:54 UTC, andyliuliming commented on src/azure-cli/azure/cli/command_modules/acs/custom.py
> +    def get_variable_from_param_and_context(self, variable_name, prefer_context=False):
comments.

2021-08-06 02:54 UTC, andyliuliming commented on src/azure-cli/azure/cli/command_modules/acs/custom.py
> +    def check_params(self):
comments.

2021-08-06 02:55 UTC, andyliuliming requested changes

2021-08-06 02:55 UTC, andyliuliming commented on src/azure-cli/azure/cli/command_modules/acs/custom.py
> +        self.param = AKSCreateParameters(raw_parameters)
can we try to add some linting rule that check the param won't be modified.

2021-08-10 04:41 UTC, andyliuliming requested changes

2021-08-10 04:41 UTC, andyliuliming commented on src/azure-cli/azure/cli/command_modules/acs/custom.py
> +            cached_value = self.get_param(parameter_name, read_raw=False, default_value=default_value)
what's the benifits?

2021-08-20 09:55 UTC, zhoxing-ms commented
What is the difference between PR #19259 and this PR? If they are the same PR, could you close it?

2021-08-23 03:23 UTC, FumingZhang commented
The modification has been replaced by PR #19259, closed,

2021-08-23 03:23 UTC, closed without merging