[App Service]: Fix #19098: `az webapp deployment slot auto-swap `: Fix the AttributeError error for parameters `--slot --disable`
Azure/azure-cli pull request #19376
Opened 2021-08-27 19:18 UTC by parth21999

**Description**

Fix #19098

`az webapp deployment slot auto-swap --name --resource-group --slot --disable` gives error.

Fix parameter order  in `update_configuration_slot`.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-08-30 08:58 UTC, zhoxing-ms commented
Because this is a bug fix, does this change need to be written into the release note?

2021-08-30 08:59 UTC, zhoxing-ms commented
Could you add some tests for this change?

2021-08-30 16:39 UTC, parth21999 commented
> @parth21999 Because this is a bug fix, does this change need to be written into the release note?

No, it doesn't need to be included in the release note. As per my understanding, `{}` meant that it shouldn't be included. Am I right?

2021-08-31 02:42 UTC, zhoxing-ms commented
@parth21999  Yes. However, we usually recommend putting the bug fixes information into the release note to let users know.

By the way, why didn't we find this bug by running the tests before? If it is because of the lack of tests, could you add some relevant tests?

2021-08-31 20:56 UTC, parth21999 commented
I've added tests to cover auto-swap.

2021-09-01 02:33 UTC, panchagnula commented on src/azure-cli/azure/cli/command_modules/appservice/custom.py
>          client.web_apps.create_or_update_configuration(resource_group_name, name, site_config)
Change the if else block to use the _generic_site_operation instead

2021-09-01 04:10 UTC, panchagnula commented on src/azure-cli/azure/cli/command_modules/appservice/custom.py
> +    return client.web_apps.update_configuration_slot(resource_group_name, webapp, slot, site_config)
Same comment here as well plus make sure to use use positional arguments here, so this doesn't cause issues in the future.

2021-09-01 04:11 UTC, panchagnula requested changes
a few comments to address. Thanks

2021-09-02 07:14 UTC, zhoxing-ms commented
@parth21999 Could you resolve these conflicts by tomorrow? Otherwise, it will not catch up with the release time of this sprint, and we will plan to release it in the next sprint **(10-05)**

2021-09-02 17:06 UTC, panchagnula approved these changes
approved

2021-09-03 00:27 UTC, zhoxing-ms approved these changes

2021-09-03 00:27 UTC, merged