Sbdev202106
Azure/azure-cli pull request #19741
Opened 2021-09-30 05:47 UTC by v-Ajnava

**Description**

>Added zone-redundant parameter to namespace create command
>Added disable-local-auth parameter to namespace create and update command
>Added new private-endpoint-connection and private-link-resource commands for namespace

**Testing Guide**

## private-endpoint-connection Commands
### Approve 

> az servicebus namespace private-endpoint-connection approve
example: 
az servicebus namespace private-endpoint-connection approve -g myRg --namespace-name mynamespace --name myconnection

### Delete 

> az servicebus namespace private-endpoint-connection delete
example: 
az servicebus namespace private-endpoint-connection delete -g myRg --namespace-name mynamespace --name myconnection

### Delete 

> az servicebus namespace private-endpoint-connection reject
example: 
az servicebus namespace private-endpoint-connection reject -g myRg --namespace-name mynamespace --name myconnection

### show

> az servicebus namespace private-endpoint-connection show
example: 
az servicebus namespace private-endpoint-connection show -g myRg --namespace-name mynamespace --name myconnection

## private-link-resource Commands
### show

> az servicebus namespace private-link-resource show
example: 
az servicebus namespace private-link-resource show --namespace-name mynamespace -g MyResourceGroup

**History Notes**

[ServiceBus] 'az servicebus namespace create' : Add `--zone-redundant` creates a ServiceBus Zone Redundant Namespace in regions supported availability zones.
[ServiceBus] 'az servicebus namespace create/update' : Add `--disable-local-auth` to enable or disable  SAS authentication.
[ServiceBus] Added new private-endpoint-connection and private-link-resource commands for namespace

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2021-09-30 06:52 UTC, yonzhan commented
ServiceBus

2021-10-08 02:42 UTC, evelyn-ys commented
/azp run

2021-12-03 03:06 UTC, wangzelin007 requested changes

2022-05-12 14:08 UTC, damodaravadhani requested changes

2022-05-12 14:08 UTC, damodaravadhani commented on src/azure-cli/azure/cli/command_modules/servicebus/custom.py
> +        private_endpoint_connection.private_link_service_connection_state.description = description
We should be updating description regardless of what updated status is right ? Shouldn't this be outside if block. and we should be updating it only if the user has given description and not other times.

2022-05-16 05:30 UTC, v-Ajnava commented
Hi @wangzelin007 and @evelyn-ys  can you please review the PR and help in in understanding the failure of test in latest profile.

2022-05-16 09:20 UTC, damodaravadhani commented
@yonzhan , can you add the May release build label to this PR ?

2022-05-16 10:59 UTC, evelyn-ys commented
/azp run

2022-05-16 10:59 UTC, evelyn-ys approved these changes

2022-05-16 11:54 UTC, wangzelin007 commented
/azp run

2022-05-16 11:58 UTC, wangzelin007 approved these changes

2022-05-16 12:09 UTC, wangzelin007 commented
/azp run

2022-05-17 03:29 UTC, damodaravadhani commented
<img width="671" alt="image" src="https://user-images.githubusercontent.com/91929893/168722519-682f3949-232f-42e3-8667-c543781f53ec.png">
@evelyn-ys , the pipelines point to a certain azure/cli/command_modules/network/tests/latest/test_network_commands.py::NetworkVirtualApplianceScenarioTest::test_network_virtual_appliance and asks us to push the recording although it doesn't use service bus in the test. Do you happen to know why this is the case? Thanks.

2022-05-17 03:38 UTC, evelyn-ys commented
@necusjz Can you help with the network test failure?

2022-05-17 04:01 UTC, zhoxing-ms approved these changes

2022-05-17 08:16 UTC, wangzelin007 commented
/azp run

2022-05-17 09:19 UTC, damodaravadhani commented
Hey @evelyn-ys, could we please merge this PR ? Thanks.

2022-05-17 10:19 UTC, merged