[Draft]
Azure/azure-cli pull request #21520
Opened 2022-03-03 23:03 UTC by StrawnSC

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change.
[Component Name 2] `az command b`: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2022-03-04 00:20 UTC, yonzhan commented
@jiasli for awareness

2022-03-07 06:49 UTC, jiasli commented
To be honest, **I personally don't agree with this change**:

- Switching the default output format from `json` to `table` is such a BREAKING CHANGE that all users and scrips relying on the JSON output of `az logout` will fail.
- We tend not to sort the subscription list because the order is returned by ARM and we simply keep it as-is.

For these messages:

![image](https://user-images.githubusercontent.com/4003950/156981165-fc22d141-604d-4e55-9bac-8669249ee156.png)

We tried to implement them via a new feature called **post-output hint** (https://github.com/Azure/azure-cli/pull/16242), but that feature got suspended.

There is also another new feature called `az init` developed by @zhoxing-ms to let the user select the output format interactively.

2022-03-07 06:50 UTC, jiasli requested changes
We need (a lot) more discussion about this BREAKING CHANGE.

2022-03-07 07:24 UTC, StrawnSC commented
> We need (a lot) more discussion about this BREAKING CHANGE.

@jiasli I definitely agree with this and apologize if this seems like an unsolicited or unneeded change. This work is all very preliminary and I opened a pull request to sharing progress and *not* to try and get these changes merged without more discussion (hence the PR is a draft and marked as do-not-merge). 

@panchagnula directed the work here and can offer more info on the rationale for this change. My understanding is that internal users were confused about the output of `az login` and wanted a better user experience for first-time users

2022-03-08 06:32 UTC, zhoxing-ms commented
> There is also another new feature called az init developed by @zhoxing-ms to let the user select the output format interactively.

Yes, this is `az init` related blog: [blog link](https://techcommunity.microsoft.com/t5/azure-tools-blog/streamline-configuring-azure-cli-with-az-init/ba-p/3051810)
`az init` adjusts the same configuration file as `az config set` and is meant to help simplify the configuration process. It's intended to quickly set up global configurations suitable for users' current environment. 
Users can execute the `az extension add -n init` command to install it. Or they can directly execute `az init` command and then complete the automatic installation through dynamic installation.

2022-03-08 20:05 UTC, panchagnula commented
> > There is also another new feature called az init developed by @zhoxing-ms to let the user select the output format interactively.
> 
> Yes, this is `az init` related blog: [blog link](https://techcommunity.microsoft.com/t5/azure-tools-blog/streamline-configuring-azure-cli-with-az-init/ba-p/3051810) `az init` adjusts the same configuration file as `az config set` and is meant to help simplify the configuration process. It's intended to quickly set up global configurations suitable for users' current environment. Users can execute the `az extension add -n init` command to install it. Or they can directly execute `az init` command and then complete the automatic installation through dynamic installation.

@zhoxing-ms thanks for sharing this blog. This is a good start. I wanted to call out though from the feedback being received that is mostly control the response object by command. i.e config will change the response type across all CLI commands, & using Set_output_format is for the command to return a subset of the object response & in a better fashion & adding some debug text on what the next steps should be. Ex, in this POC , text showing how to set the default subscription  post login was added.

2022-10-20 16:52 UTC, closed without merging