[AKS] az aks check-acr: Bump canipull to 0.0.5-alpha to add 5s wait to avoid attach race condition
Azure/azure-cli pull request #23087
Opened 2022-07-01 05:16 UTC by fseldow

**Related command**

**Description**

add 5s wait to avoid attach race condition
**Testing Guide**

ran e2e test pipeline
**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2022-07-01 05:37 UTC, FumingZhang commented
Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=57219841&view=results) to test the modified `check-acr` command.

2022-07-01 05:49 UTC, yonzhan commented
AKS

2022-07-01 07:12 UTC, FumingZhang approved these changes
LGTM :shipit:

2022-07-01 14:44 UTC, andyliuliming approved these changes

2022-07-01 14:46 UTC, andyliuliming requested changes

2022-07-01 14:46 UTC, andyliuliming commented on src/azure-cli/azure/cli/command_modules/acs/_consts.py
> +CONST_CANIPULL_IMAGE = "mcr.microsoft.com/aks/canipull:0.0.5-alpha"
+-----------------------------+------------------+----------+---------------------+-------------------------------------+---------------------------------------+
|           LIBRARY           | VULNERABILITY ID | SEVERITY |  INSTALLED VERSION  |            FIXED VERSION            |                 TITLE                 |
+-----------------------------+------------------+----------+---------------------+-------------------------------------+---------------------------------------+
| github.com/dgrijalva/jwt-go | CVE-2020-26160   | HIGH     | v3.2.0+incompatible |                                     | jwt-go: access restriction            |
|                             |                  |          |                     |                                     | bypass vulnerability                  |
|                             |                  |          |                     |                                     | -->avd.aquasec.com/nvd/cve-2020-26160 |
+-----------------------------+------------------+          +---------------------+-------------------------------------+---------------------------------------+
| github.com/gogo/protobuf    | CVE-2021-3121    |          | v1.3.1              | 1.3.2                               | gogo/protobuf:                        |
|                             |                  |          |                     |                                     | plugin/unmarshal/unmarshal.go         |
|                             |                  |          |                     |                                     | lacks certain index validation        |
|                             |                  |          |                     |                                     | -->avd.aquasec.com/nvd/cve-2021-3121  |
+-----------------------------+------------------+----------+---------------------+-------------------------------------+---------------------------------------+
| github.com/satori/go.uuid   | CVE-2021-3538    | CRITICAL | v1.2.0              | 1.2.1-0.20181016170032-d91630c85102 | satori/go.uuid: predictable UUIDs     |
|                             |                  |          |                     |                                     | generated via insecure randomness     |
|                             |                  |          |                     |                                     | -->avd.aquasec.com/nvd/cve-2021-3538  |
+-----------------------------+------------------+----------+---------------------+-------------------------------------+---------------------------------------+
| golang.org/x/text           | CVE-2021-38561   | HIGH     | v0.3.4              | 0.3.7                               | golang: out-of-bounds read            |
|                             |                  |          |                     |                                     | in golang.org/x/text/language         |
|                             |                  |          |                     |                                     | leads to DoS                          |
|                             |                  |          |                     |                                     | -->avd.aquasec.com/nvd/cve-2021-38561 |

2022-07-03 15:26 UTC, andyliuliming commented
need to modify the title.

2022-07-04 04:24 UTC, andyliuliming approved these changes

2022-07-04 04:25 UTC, andyliuliming commented
please also paste the testing result here.

2022-07-04 04:27 UTC, fseldow commented on src/azure-cli/azure/cli/command_modules/acs/_consts.py
> +CONST_CANIPULL_IMAGE = "mcr.microsoft.com/aks/canipull:0.0.5-alpha"
2022-07-04T04:26:56.366Z        INFO    Need to update DB
2022-07-04T04:26:56.368Z        INFO    Downloading DB...
28.48 MiB / 28.48 MiB [---------------------------------------------------------------------------------------------] 100.00% 11.54 MiB p/s 2s
2022-07-04T04:26:59.835Z        INFO    Detecting Debian vulnerabilities...
2022-07-04T04:26:59.836Z        INFO    Trivy skips scanning programming language libraries because no supported file was detected

mcr.microsoft.com/aks/canipull:v0.1.0 (debian 11.3)
===================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

2022-07-04 04:28 UTC, fseldow commented
2022-07-04T04:26:56.366Z        INFO    Need to update DB
2022-07-04T04:26:56.368Z        INFO    Downloading DB...
28.48 MiB / 28.48 MiB [---------------------------------------------------------------------------------------------] 100.00% 11.54 MiB p/s 2s
2022-07-04T04:26:59.835Z        INFO    Detecting Debian vulnerabilities...
2022-07-04T04:26:59.836Z        INFO    Trivy skips scanning programming language libraries because no supported file was detected

mcr.microsoft.com/aks/canipull:v0.1.0 (debian 11.3)
===================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

2022-07-05 01:49 UTC, zhoxing-ms approved these changes

2022-07-05 01:50 UTC, merged