{AKS} Fix #17681: Fix `az aks create` error if name contains characte…
Azure/azure-cli pull request #23272
Opened 2022-07-20 09:30 UTC by RakeshMohanMSFT

…r underscore

Fixes https://github.com/Azure/azure-cli/issues/17681

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2022-07-20 10:26 UTC, yonzhan commented
AKS

2022-07-21 04:32 UTC, FumingZhang requested changes

2022-07-21 04:32 UTC, FumingZhang commented on src/azure-cli/azure/cli/command_modules/acs/_validators.py
> +    rfc1123_regex = re.compile(r'^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-\_]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-\_]{0,61}[a-zA-Z0-9]))*$')  # pylint:disable=line-too-long
I checked the regex used in aks-rp, should be `^[a-zA-Z0-9]$|^[a-zA-Z0-9][-_a-zA-Z0-9]{0,61}[a-zA-Z0-9]$`.
// singleCharacter ^[a-zA-Z0-9]$ or
// more than 2 character with hyphen underscore in middle ^[a-zA-Z0-9][-_a-zA-Z0-9]{0,61}[a-zA-Z0-9]$
// max length = 63

```suggestion
    rfc1123_regex = re.compile(r'^[a-zA-Z0-9]$|^[a-zA-Z0-9][-_a-zA-Z0-9]{0,61}[a-zA-Z0-9]$')  # pylint:disable=line-too-long
```

2022-07-21 04:32 UTC, FumingZhang commented on src/azure-cli/azure/cli/command_modules/acs/_validators.py
> +                       'The name must start and end with letter or number.')
Please the info about cannot exceed 63 characters.

2022-07-21 05:03 UTC, FumingZhang approved these changes
LGTM

2022-07-21 06:18 UTC, merged