[Network] Fix #22594: `az network bastion create`: Add no wait support for bastion create
Azure/azure-cli pull request #23467
Opened 2022-08-08 22:16 UTC by PramodValavala-MSFT

**Related command**

```sh
az network bastion create --name {} --resource-group {} --vnet-name {} --public-ip-address {} --no-wait
az network bastion wait --name {} --resource-group {} --created
```

**Description**

This PR adds `--no-wait` support (and the corresponding `wait` command) to `az network bastion`, allowing for no wait scenarios where one does not need to wait for bastion creation to complete.

Resolves #22594

**Testing Guide**

Follow [this section](https://docs.microsoft.com/en-us/azure/bastion/create-host-cli#createhost) except that the last command should also include the `--no-wait` argument. Then, the following command can be run (typically later in a script as required)

```sh
az network bastion wait --name {} --resource-group {} --created
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2022-08-08 22:24 UTC, yonzhan commented
Network

2022-08-17 03:02 UTC, necusjz approved these changes

2022-08-17 03:03 UTC, necusjz requested changes
CI needs to be fixed: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1785071&view=logs&j=168ccbe3-da49-5c0b-6478-08f7016e4bf5&t=10a595be-4223-5cc7-9a73-012871b6eaee&l=167

2022-08-24 17:08 UTC, PramodValavala-MSFT commented
@necusjz I've made the required changes and looks all green now. 👍

2022-08-25 02:17 UTC, necusjz approved these changes

2022-08-25 02:17 UTC, merged