Draft pr
Azure/azure-cli pull request #24642
Opened 2022-11-14 09:06 UTC by tguxia

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2022-11-14 11:55 UTC, yonzhan commented
network

2022-11-15 03:04 UTC, necusjz requested changes
The title of this PR is a little bit rough, could you please refine it? As well as the linter/style checks.

2022-11-15 03:14 UTC, necusjz commented on src/azure-cli/azure/cli/command_modules/network/_params.py
> +        c.argument('public_ip_address', required=False, options_list=['--public-ip-addresses'], nargs='+', help='Specify a single public IP (name or ID) for an active-standby gateway. Specify two spa
We don't need to explicitly declare "required or not". It's determined by the function signature in _custom.py_ (positional or keyword).

2022-11-15 03:16 UTC, necusjz commented on src/azure-cli/azure/cli/command_modules/network/_params.py
> +        c.argument('VNetExtendedLocationResourceId', VNetExtendedLocationResourceId, min_api='2021-02-01')
"min_api='2021-02-01" seems redundant.

2022-12-08 04:15 UTC, necusjz commented on src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py
> +        })
```suggestion
        self.kwargs.update({
            'rg': resource_group,
            'vnet': 'vnet',
            'gateway_type' : 'LocalGateway',
            'edge_name': 'microsoftrrdclab3',
        })
```
It's useless as we declare it later.

2022-12-08 05:58 UTC, merged