Update cli code for the new sdk package and update tests by rerecording
Azure/azure-cli pull request #24997
Opened 2022-12-28 14:19 UTC by ambrahma

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2022-12-28 23:07 UTC, yonzhan commented
rdbms

2023-01-17 02:07 UTC, alanenriqueo requested changes

2023-01-17 14:09 UTC, ambrahma commented on src/azure-cli/azure/cli/command_modules/rdbms/_helptext_pg.py
> +      # create flexible server with aad auth and password auth enabled
Fixed

2023-01-18 03:48 UTC, ambrahma commented
azp -run

2023-01-18 03:50 UTC, ambrahma commented
/azp run

2023-01-18 03:52 UTC, alanenriqueo commented
/azp run

2023-01-18 03:53 UTC, alanenriqueo approved these changes

2023-01-18 07:20 UTC, evelyn-ys approved these changes

2023-01-18 08:59 UTC, merged