[RDBMS] `az postgres flexible-server migration`: Use Cloud supplied URL's rather than hardcoded management URL's
Azure/azure-cli pull request #25332
Opened 2023-02-02 07:28 UTC by cpj2195

**Description**
Earlier, The management URLs were hardcoded because of which the CLI was unusable in the national clouds.
With this change, the CLI will work for all clouds when the user selects the cloud.

**Testing Guide**
Tested manually in the local environment.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2023-02-02 11:42 UTC, yonzhan commented
RDBMS

2023-02-02 17:48 UTC, DaeunYim commented
Just wanted to make sure if this one is tested in the mooncake region?

2023-02-02 18:23 UTC, alanenriqueo requested changes

2023-02-02 18:23 UTC, alanenriqueo commented on src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
> +    r = send_raw_request(cmd.cli_ctx, "get", cmd.cli_ctx.cloud.endpoints.resource_manager + "subscriptions/{}/resourceGroups/{}/providers/Microsoft.DBforPostgreSQL/flexibleServers/{}/migrations/{}?ap
`cmd.cli_ctx.cloud.endpoints.resource_manager` may or may not contain trailing `/`. An easy way to fix this is just remove `https://management.azure.com`, function `send_raw_request` will take care of appending the current cloud resource manager endpoint correctly.

2023-02-03 08:38 UTC, cpj2195 commented
> Just wanted to make sure if this one is tested in the mooncake region?

@DaeunYim , the FMS based migrations are not available in Mooncake region right now. Since we have removed the hardcoded management URL's, should it work out of the box?

2023-02-03 20:18 UTC, alanenriqueo approved these changes

2023-02-03 21:48 UTC, alanenriqueo commented on src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_common.py
> +    server_endpoint = cmd.cli_ctx.cloud.suffixes.postgresql_server_endpoint
Remove this unused variable so style check passes.

2023-02-09 05:40 UTC, alanenriqueo approved these changes

2023-02-09 05:45 UTC, evelyn-ys approved these changes

2023-02-09 05:46 UTC, merged