{ACR} Fix #24886: `az acr`: Improve the 429 error handling for CONNECTIVITY_REFRESH_TOKEN_ERROR
Azure/azure-cli pull request #25549
Opened 2023-02-23 09:52 UTC by jasminetMSFT

**Related command**

`az acr`

**Description**

This PR updates the error message that appears when "CONNECTIVITY_REFRESH_TOKEN_ERROR, Response code: 429" occurs. The original message "Please try running 'az login' again to refresh permissions" is misleading and is now replaced with a more accurate message to ask the user to retry.

Fix #24886 

**Testing Guide**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2023-02-23 09:55 UTC, jasminetMSFT commented
/cc @shizhMSFT @Wwwsylvia

2023-02-23 11:10 UTC, yonzhan commented
ACR

2023-02-24 08:21 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_errors.py
> +)
Should we have a generic `CONNECTIVITY_TOOMANYREQUESTS_ERROR`, which is not specific to refresh token? Just like `CONNECTIVITY_FORBIDDEN_ERROR`?

2023-02-24 08:21 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +        logger.warning("%s: %s  CLI will attempt to get credentials with username and password.",
nit: double space
```suggestion
        logger.warning("%s: %s CLI will attempt to get credentials with username and password.",
```

2023-02-24 08:21 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +                           AAD_TOKEN_BASE_ERROR_MESSAGE, str(e))
The revised warning message is too verbose since line 420 already tells.

2023-02-24 08:21 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +                       ADMIN_USER_BASE_ERROR_MESSAGE, resource_not_found)
What's the purpose of adding those verbose strings?

2023-02-27 09:03 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_errors.py
> +    "Too many requests, access to registry '{}' was denied. Response code: 429. Please wait a moment before trying again."
nit: we don't need to expose the response code to the customers.
```suggestion
    "Too many requests, access to registry '{}' was denied. Please wait a moment before trying again."
```

2023-02-27 09:26 UTC, shizhMSFT approved these changes
LGTM

2023-02-27 09:36 UTC, shizhMSFT requested changes

2023-02-27 09:36 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +def raise_tomanyrequests_error(error):
typo:
```suggestion
def raise_toomanyrequests_error(error):
```

2023-02-27 09:37 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_errors.py
nit: code style: missing empty line?

2023-02-27 09:44 UTC, shizhMSFT commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +    if '429' in error:
String match seems not a good solution. Will it cause false positives?

2023-02-28 12:00 UTC, Wwwsylvia submitted a review, later dismissed
LGTM

2023-03-01 01:45 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +                       .get_error_message())
Could you please use the specific error type from `azure.cli.core.azclierror` instead of `CLIError`

2023-03-01 01:46 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py
> +        raise CLIError("{}: {}".format(AAD_TOKEN_BASE_ERROR_MESSAGE, error))
Same as above

2023-03-02 03:33 UTC, zhoxing-ms approved these changes

2023-03-02 03:33 UTC, merged