{Service Connector} 'az spring connection create': Enable user-assigned managed identity for spring apps [Service Connector] 'az webapp/spring/containerapp connection create postgres': Deprecate Postgresql
Azure/azure-cli pull request #26259
Opened 2023-04-26 04:40 UTC by wchigit

**Related command**

az spring connection create [target-resource-type] --user-identity client-id=[client-id] subs-id=[subscription-id]

az webapp connection create postgres
az spring connection create postgres
az containerapp connection create postgres

**Description**

User-assigned managed identity is enabled as an auth type for spring apps to create connections.

Deprecate the Postgresql.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2023-04-26 09:39 UTC, yonzhan commented
Service Connector

2023-04-27 02:25 UTC, yungezz submitted a review, later dismissed

2023-04-27 02:51 UTC, houk-ms requested changes
**PR title**
Adding new auth types is a customer facing feature and we need use `[Service Connector]`

**CredScan**
Check current `recording_precessor` in the ScenarioTest def and adding your own rules to hide credentials

2023-04-27 02:51 UTC, houk-ms commented on src/azure-cli/azure/cli/command_modules/serviceconnector/commands.py
> +                    if target == RESOURCE.Mysql or target == RESOURCE.Postgres:
may define the targets to be deprecated in `_resource_configs.py`

2023-04-27 02:51 UTC, houk-ms commented on src/azure-cli/azure/cli/command_modules/serviceconnector/tests/latest/recordings/test_springcloud_cosmossql_umi.yaml
> +        {"name": "azure.cosmos.key", "value": "4AfKEpKdsxibgloPh0Y4dXB8nSNzddl8HRzku3vFz9PpLF11JvYiuydgkZJNOasED5mGm8hIDfTX6XGyQR5PUQ=="},
need hide these credentials, consider using/adding `recording_processors` in you tests

also check other cases in CredScan results

2023-04-27 02:54 UTC, houk-ms commented
Not sure whether the title could be parsed or not, a better way is to create two PRs for two feature changes :)

2023-05-05 08:09 UTC, xfz11 approved these changes

2023-05-05 08:26 UTC, houk-ms approved these changes
hi @kairu-ms, please help review the PR when available

2023-05-05 08:46 UTC, kairu-ms approved these changes

2023-05-05 08:46 UTC, merged