[ACR] Add additional parameter validation to `az acr login`
Azure/azure-cli pull request #27762
Opened 2023-11-03 21:20 UTC by mabenedi

**Related command**
`az acr login`
**Description**

Adds additional parameter validation for `az acr login`
**Testing Guide**

`az acr login -n myregistry` -> good
`az acr login -n myregistry$` -> throw error
**History Notes**
[ACR] `az acr login`: Add additional parameter validation
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2023-11-03 21:20 UTC, yonzhan commented
<!-- add-pr-comment:add-pr-comment -->

ACR

2023-11-04 13:11 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/acr/_validators.py
> +    pattern = r'^[a-zA-Z0-9]{5,50}$'
Please add a comment to explain the purpose of this regular expression

2023-11-04 13:13 UTC, zhoxing-ms commented
Could you have other engineers in your team review and sign off this PR as well? @mabenedi

2023-11-06 06:23 UTC, zhoxing-ms commented
Please note that we are launching the release for this sprint this week. Please resolve all comments by xxx, otherwise the release of this PR will have to be postponed to the next sprint **(on 12-05)**

2023-11-06 19:22 UTC, SakoPak approved these changes

2023-11-07 01:35 UTC, rosanch requested changes
Other than that, one comment LGTM

2023-11-07 01:35 UTC, rosanch commented on src/azure-cli/azure/cli/command_modules/acr/_validators.py
> +    pattern = r'^[a-zA-Z0-9]{5,50}$'
can you move this to the constants file please?

2023-11-07 01:46 UTC, rosanch approved these changes
LGTM

2023-11-07 04:28 UTC, zhoxing-ms approved these changes

2023-11-07 04:30 UTC, merged