[Backup] AFS VaultStandard
Azure/azure-cli pull request #30531
Opened 2024-12-17 06:30 UTC by IannGeorges

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

2024-12-17 06:30 UTC, yonzhan commented
Thank you for your contribution! We will review the pull request and get back to you soon.

2024-12-24 04:06 UTC, IannGeorges commented
@yonzhan @zhoxing-ms Could you please re-trigger the pipeline, I want to download private build for bug bash

2024-12-27 07:48 UTC, zubairabid requested changes

2024-12-27 07:48 UTC, zubairabid commented on src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
> +            if rp_tier == tier:
are we just ignoring the tier parameter otherwise? We should inform the customer with a warning of some sorts, I think.

2024-12-27 07:48 UTC, zubairabid commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if hasattr(existing_policy.properties, 'vault_retention_policy') and existing_policy.properties.vault_retention_policy is not None and hasattr(new_policy.properties, 'retention_policy') and new_p
this is being run for all policies, not just AFS. Is that desired?

2024-12-27 07:48 UTC, zubairabid commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if not yes and hasattr(existing_policy.properties, 'retention_policy') and existing_policy.properties.retention_policy is not None and hasattr(new_policy.properties, 'vault_retention_policy') and
If `yes` is passed as `True`, we never enter this path anyway. If the goal is to have `yes` skip the warning prompt, we need to remove the check from this line and add it lower down in 692: `if yes or not prompt_y_n(warning_prompt)`.

2024-12-27 07:48 UTC, zubairabid commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +                          'Learn more at https://learn.microsoft.com/en-us/azure/backup/azure-file-share-backup-overview?tabs=snapshot.')
Instruct the user here. Right now it's just a statement asking for a y/n input, and if they press "no" then the operation gets cancelled. Add a line that says "do you want to continue"

2024-12-27 07:48 UTC, zubairabid commented on src/azure-cli/azure/cli/command_modules/backup/tests/latest/preparers.py
>  class AFSPolicyPreparer(AbstractPreparer, SingleValueReplacer):
1. We don't need `instant_rp_days` anymore?
2. The code you've added for creating a new AFS policy seems fine, but it looks like the AFSPolicyPreparer already existed and presumably is used for some tests. Are you sure that your changes will not break other tests?

2024-12-27 09:19 UTC, zhoxing-ms commented
/azp run

2025-01-03 10:54 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
> +            if rp_tier == tier:
Fixed code to show customer warning with valid rp_tier types for AFS.

2025-01-03 10:57 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if hasattr(existing_policy.properties, 'vault_retention_policy') and existing_policy.properties.vault_retention_policy is not None and hasattr(new_policy.properties, 'retention_policy') and new_p
This validation is currently only being called for AFS at the moment; however I could add a validation to check for the backup management type to ensure it's only AzureStorage or find way to validate that it is AFS?

2025-01-03 10:58 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +                          'Learn more at https://learn.microsoft.com/en-us/azure/backup/azure-file-share-backup-overview?tabs=snapshot.')
Done

2025-01-03 11:00 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/tests/latest/preparers.py
>  class AFSPolicyPreparer(AbstractPreparer, SingleValueReplacer):
1. Yes instant_rp_days doesn't exist on AFS policy and service side is ignoring the key/value pair within AFS policies.
2. AFSPolicyPreparers is only being used within test_afs_commands

2025-01-03 11:02 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if not yes and hasattr(existing_policy.properties, 'retention_policy') and existing_policy.properties.retention_policy is not None and hasattr(new_policy.properties, 'vault_retention_policy') and
If user passes yes then wouldn't this trigger the cli error? In any case would it be okay I removed the yes conditional all together so that all customers are aware of warning?

2025-01-03 12:42 UTC, zubairabid reviewed
Looks good, just need a couple of minor changes

2025-01-03 12:42 UTC, zubairabid commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if hasattr(existing_policy.properties, 'vault_retention_policy') and existing_policy.properties.vault_retention_policy is not None and hasattr(new_policy.properties, 'retention_policy') and new_p
azure storage check should work

2025-01-05 10:59 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if hasattr(existing_policy.properties, 'vault_retention_policy') and existing_policy.properties.vault_retention_policy is not None and hasattr(new_policy.properties, 'retention_policy') and new_p
Done

2025-01-05 11:06 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_afs.py
> +            if rp_tier == tier:
Changed to warning message, should I return all of the rp's even if the rp_tier_types are neither InstantRP nor HardenedRP?

2025-01-16 23:08 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/_params.py
> +        c.argument('yes', options_list=['--yes', '-y'], help='Skip confirmation when updating Standard to Enhanced Policies.', action='store_true')
Hey @zhoxing-ms, I have added the --yes param back into the command logic. --yes will allow users to force run the **az backup policy set** & **az backup item set-policy** commands in order to bypass the warning when switching from snapshot to vaulted backup policies. This param is used within validate_update_policy_request function in the custom_help file.

2025-01-17 07:27 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/backup/_params.py
> +        c.argument('yes', options_list=['--yes', '-y'], help='Skip confirmation when updating Standard to Enhanced Policies.', action='store_true')
got it, thanks

2025-01-17 07:29 UTC, zhoxing-ms commented
Please refer to this document [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests) to improve the PR title

2025-01-22 02:08 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if new_backup_management_type.lower() == 'azurestorage' and hasattr(existing_policy.properties, 'vault_retention_policy') and existing_policy.properties.vault_retention_policy is not None and has
> if new_backup_management_type.lower() == 'azurestorage' and hasattr(existing_policy.properties, 'vault_retention_policy') 

The newly added judgment logic is too complex. Could it be abstracted as a variable to reduce the complexity of code

2025-01-22 02:09 UTC, zhoxing-ms commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if new_backup_management_type.lower() == 'azurestorage' and hasattr(existing_policy.properties, 'retention_policy') and existing_policy.properties.retention_policy is not None and hasattr(new_pol
Same as above

2025-01-22 03:50 UTC, IannGeorges commented on src/azure-cli/azure/cli/command_modules/backup/custom_help.py
> +    if new_backup_management_type.lower() == 'azurestorage' and hasattr(existing_policy.properties, 'vault_retention_policy') and existing_policy.properties.vault_retention_policy is not None and has
@zhoxing-ms Thanks for the feedback, I have refactored the code

2025-01-22 04:05 UTC, zhoxing-ms approved these changes

2025-01-22 07:32 UTC, zhoxing-ms commented
/azp run

2025-01-24 08:08 UTC, yanzhudd commented
Please resolve CI issues.

2025-01-24 08:08 UTC, yanzhudd commented
Please note Azure CLI will freeze the code on 01/28/2025 10:00 UTC for the upcoming release. If you want to catch this release train, please get this PR ready ASAP, otherwise it has to be postponed to next sprint.

2025-01-24 14:55 UTC, IannGeorges commented
@yanzhudd @yonzhan @jsntcy Whenever you have a moment could you please rerun the pipeline? I have addressed the CI linting issues. @zhoxing-ms has already approved, merge was pending CI checks.

2025-01-24 16:51 UTC, IannGeorges commented
I believe CI is flaky, could you please run the pipeline again? @yonzhan

2025-01-24 23:43 UTC, yonzhan commented
/azp run

2025-01-25 02:03 UTC, IannGeorges commented
My apologies but could you please rerun the CI once more? Addressed the remaining linting errors @yonzhan

2025-01-25 08:26 UTC, yonzhan commented
/azp run

2025-01-25 23:31 UTC, yonzhan commented
CI is still failing.

2025-01-26 01:47 UTC, IannGeorges commented
@yonzhan Sorry for the inconvenience, could you please run the CI? Linting issues should be resolved now with latest change ...

2025-01-26 02:07 UTC, yonzhan commented
/azp run

2025-01-26 03:09 UTC, yanzhudd approved these changes

2025-01-26 03:09 UTC, merged